### PR TITLE
Release version 1.4.0

### PR DESCRIPTION
**Pull request by prashantv**
Changes since v1.3.0:
* Add version information to the channel's LocalPeerInfo.
* Add peers package for peer management utilities such as
  consistent peer selection.
* Fix SetScoreStrategy not rescoring existing peers. (#583).

### CODE REVIEW

**Comment by alxn** [comment]
@prashantv :sad: :panda:

```
PASS
coverage: 89.0% of statements
Found 3 data race(s)
exit status 66
FAIL	github.com/uber/tchannel-go	34.081s
```

**Comment by prashantv** [comment]
Yep, the usual data race in tests which close while during the connection handshake.

Ideally we would fix the race before release -- are you OK with delaying the release for a day?

**Comment by alxn** [comment]
@prashantv Makes sense to me.

**Comment by alxn** [comment]
@prashantv a day is a long time in software engineering... :-P

**Pull request merged**
