### PR TITLE
Expose relay span setting in relayer

### PR DESCRIPTION
**Pull request by Yu-Xie**
Expose SetRelaySpan to CallFrame interface. It allows relaying services to report their own spans.

### CODE REVIEW

**Comment by prashantv** [comment]
@Yu-Xie I was chatting with @kriskowal and @willhug about this change, and we realized this probably won't work since tracing is propagated in headers. For backwards compatibility, it's also added to the call frame, but the clients will use the headers when available.

The headers are in arg2, and there's no efficient way to read/write arg2.

You might have to use TChannel as a normal client (using the arg reader + writer) to get this working.

**Comment by Yu-Xie** [comment]
@prashantv @kriskowal, it looks when tracing information is in call frame, it will be used from there ([extractInboundSpan](https://github.com/uber/tchannel-go/blob/dev/tracing.go#L193)), and the headers will only be used for baggages. Otherwise the headers are used ([ExtractInboundSpan](https://github.com/uber/tchannel-go/blob/dev/tracing.go#L225)).

**Comment by prashantv** [comment]
@Yu-Xie I'm not sure if that's guaranteed across implementations -- E.g., what about Java, Node and Python?

**Comment by Yu-Xie** [comment]
@prashantv Yeah, that's right. Going to close this PR.

**Pull request closed without merging**
