### PR TITLE
Add PeerList.Remove for removing a peer

### LINKED ISSUE #184: Add a method of removing a peer.
We'll need this in order to keep the peer list in sync with  ip:ports obtained from DNS.

Alternatively, we could add DNS resolution & re-resolution to the channel library and avoid the need to manage peers in the application.

### PR DESCRIPTION
**Pull request by prashantv**
Resolves #184 

cc @nomis52

### CODE REVIEW

**Comment by nomis52** [comment]
LGTM

**Comment by akshayjshah** [comment]
:shipit:

**Comment by junchaowu** [comment]
Right now which case Go will remove peer?

**Comment by prashantv** [comment]
See #184. It's useful for services that talk to other TChannel services using DNS, and need to maintain the peer list in sync with the DNS entries.

**Pull request merged**
